#!/usr/bin/env zsh

# secretlint config
# SEE: https://github.com/secretlint/secretlint/blob/master/docs/configuration.md
CONFIG='{
  "rules": [
    {
      "id": "@secretlint/secretlint-rule-preset-recommend"
    }
  ]
}'

# check staged changes
git diff --cached --name-only --diff-filter=d | xargs secretlint --secretlintrc <(echo "$CONFIG")
