#!/usr/bin/env zsh

# set config
# SEE: https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-conventional
CONFIG="
extends:
  - '@commitlint/config-conventional'
rules:
  body-max-line-length: [0, 'always', Infinity]
  footer-max-line-length: [0, 'always', Infinity]
"

# exec commitlint
commitlint --edit "$1" --config <(echo "$CONFIG")
